config/routes.rb
Rails.application.routes.draw do
  get 'posts/random'
  get 'posts/my_posts'
  get 'terms_of_service', to: 'tops#terms_of_service'
  get 'privacy_policy', to: 'tops#privacy_policy'

  patch 'users/update_notification_settings', to: 'users#update_notification_settings', as: 'update_notification_settings'

  root "tops#show"

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :posts do
    resources :comments
    collection do
      get :likes
    end
  end

  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[new create edit update show]

end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :user

  validates :name, presence: true, length: { maximum: 255 }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  def show; end

  private

  def profile_params
    params.require(:profile).permit(:name, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<label class="form-control w-full max-w-xs">

  <%= form_with model: @profile, url: profile_path do |f| %>
    <div class="label">
      <span class="label-text font-bold text-lg mt-2">ユーザー名（必須）</span>
    </div>
      <%= f.text_field :name, placeholder: "ここに入力", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>

    <div class="label">
      <span class="label-text font-bold text-lg mt-2">アバター画像（任意）</span>
    </div>
      <%= f.file_field :avatar, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>

    <button class="btn btn-primary mt-4">
      <span class="label-text-alt"><%= f.submit "登録" %></span>
    </button>
  <% end %>
</label>

app/views/profiles/edit.html.erb
<%= render 'form', { profile: @profile } %>

app/views/profiles/new.html.erb
<%= render 'form', { profile: @profile } %>

app/views/profiles/show.html.erb
<div>
  <h1 class="font-bold text-2xl">マイページ</h1>

  <div class="container mx-auto px-2">
    <div class="font-bold text-lg my-4">ユーザー名</div>
      <p><%= current_user.profile.name %></p>
    <div class="font-bold text-lg my-4">アバター画像</div>
      <p><%= image_tag current_user.profile.avatar.url, size: '100x100'%></p>
  </div>

  <button class="btn btn-primary my-4">
  <%= link_to "ユーザー情報を変更する", edit_profile_path %>
  </button>

  <% if user_signed_in? %>
    <%= form_with url: update_notification_settings_path, method: :patch do %>
      <%= hidden_field_tag :line_notifications, !current_user.line_notifications %>
      <%= submit_tag(current_user.line_notifications ? 'LINE通知をオフにする' : 'LINE通知を受け取る', class: 'btn btn-secondary') %>
    <% end %>
  <% end %>
</div>