config/routes.rb
Rails.application.routes.draw do
  get 'posts/random'
  get 'posts/my_posts'
  get 'terms_of_service', to: 'tops#terms_of_service'
  get 'privacy_policy', to: 'tops#privacy_policy'

  patch 'users/update_notification_settings', to: 'users#update_notification_settings', as: 'update_notification_settings'

  root "tops#show"

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :posts do
    resources :comments
    collection do
      get :likes
    end
  end

  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[new create edit update show]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 255 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ edit update destroy ]

  def create
    @comment = current_user.comments.build(comment_params)
    @post = Post.find(comment_params[:post_id])

    respond_to do |format|
      if @comment.save
        format.turbo_stream
        format.html { redirect_to post_path(@post) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_comment", partial: "comments/form", locals: { post: @post, comment: @comment }) }
        format.html { render "posts/show", status: :unprocessable_entity }
      end
    end
  end

  def edit
    @post = Post.find(params[:post_id])
  end

  def update
    @post = @comment.post

    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@comment) }
      format.html { redirect_to post_path(@post), notice: "コメントを削除しました。" }
    end
  end

  private

  def set_comment
    @comment = current_user.comments.find_by(id: params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>

  <div class="chat chat-start ml-12">
    <div class="chat-bubble chat-bubble-accent">

      <%= simple_format(comment.body) %>

        <div class="card-actions justify-end">
          <% if current_user.own?(comment) %>
            <%= link_to edit_post_comment_path(@post, comment) do %>
              <i class="fa-solid fa-pen-to-square fa-sm" style="color:#e69b5a"></i>
            <% end %>
            <%= button_to post_comment_path(@post, comment), method: :delete do %>
              <i class="fa-solid fa-trash fa-sm" style="color:#4682b4"></i>
            <% end %>
          <% end %>

        </div>

    </div>
  </div>

  <div class="flex items-center mb-4">
    <%= image_tag comment.user.profile.avatar.url(:index_size), class: "w-10 h-10 rounded-full object-cover mr-2" %>
    <%= comment.user.profile.name %>
  </div>

<% end %>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <%= render @comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<%= turbo_frame_tag comment do %>

  <%= form_with model: [ @post, comment ] do |f| %>

    <div class="flex justify-center">
      <% f.label :body %>
      <%= f.text_area :body, placeholder: "コメントする", class: "textarea textarea-bordered textarea-sm w-full max-w-xs" %>
    </div>

    <div class="flex justify-end my-4 mr-4">
      <%= f.submit "送信", class: "btn btn-primary" %>
    </div>

  <% end %>

<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "comments", partial: "comments/comment", locals: { comment: @comment } %>

<%= turbo_stream.replace "new_comment", partial: "comments/form", locals: { post: @post, comment: Comment.new } %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>

app/views/comments/edit.html.erb
<%= render  "comments/form", comment: @comment  %>