config/routes.rb
Rails.application.routes.draw do
  get 'posts/random'
  get 'posts/my_posts'
  get 'terms_of_service', to: 'tops#terms_of_service'
  get 'privacy_policy', to: 'tops#privacy_policy'

  patch 'users/update_notification_settings', to: 'users#update_notification_settings', as: 'update_notification_settings'

  root "tops#show"

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :posts do
    resources :comments
    collection do
      get :likes
    end
  end

  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[new create edit update show]

end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <%= link_to image_tag('logo.png'), root_path, style: "width: 250px;" %>
    </div>
    <div class="justify-center">
      <button class="btn btn-accent">
      <%= link_to "LINEログイン", user_line_omniauth_authorize_path, method: :post %>
      </button>
    </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %></p>
  <% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-base-300 text-base-content">
  <nav class="grid grid-flow-col gap-4">
    <p>© 2024 - 作業のオトモ</p>
    <p><%= link_to "利用規約", terms_of_service_path %></p>
    <p><%= link_to "プライバシーポリシー", privacy_policy_path %></p>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="flex-none">
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn m-1">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16">
          </path></svg></div>
            <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
              <li><%= link_to "投稿する", new_post_path %></li>
              <li><%= link_to "投稿一覧", posts_path %></li>
              <li><%= link_to "ランダムピックアップ", posts_random_path %></a></li>
              <li><%= link_to "自分の投稿一覧", posts_my_posts_path %></li>
              <li><%= link_to "お気に入り一覧", likes_posts_path %></li>
              <li><%= link_to "マイページ", profile_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %></li>
            </ul>
        </div>
      </div>
      <%= link_to image_tag('logo.png'), root_path, style: "width: 250px;" %>
    </div>
  </div>
</header>