config/routes.rb
Rails.application.routes.draw do
  get 'posts/random'
  get 'posts/my_posts'
  get 'terms_of_service', to: 'tops#terms_of_service'
  get 'privacy_policy', to: 'tops#privacy_policy'

  patch 'users/update_notification_settings', to: 'users#update_notification_settings', as: 'update_notification_settings'

  root "tops#show"

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :posts do
    resources :comments
    collection do
      get :likes
    end
  end

  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[new create edit update show]

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PostImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 255 }

  enum category: { food: 0, drink: 1 }

  scope :eaten, -> { where(eaten: true) }
  scope :smelly, -> { where(smell: true) }
  scope :noisy, -> { where(sound: true) }
  scope :spilly, -> { where(spill: true) }
  scope :dirty_hands, -> { where(hands_dirty: true) }
  scope :by_category, ->(category) { where(category: category) if category.present? }
  scope :recent, -> { order(created_at: :desc) }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ edit update destroy ]
  before_action :search_post, only: %i[ index ]
  before_action :store_user_return_to, only: %i[ random ]

  def index ;end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "投稿しました" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "投稿を更新しました" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "投稿を削除しました" }
      format.json { head :no_content }
    end
  end

  def random
    @post = Post.order(Arel.sql('RANDOM()')).first
  end

  def my_posts
    @posts = current_user.posts.recent.page(params[:page])

  end

  def likes
    @posts = current_user.like_posts.recent.page(params[:page])
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def search_post
      @posts = Post.all.recent.page(params[:page])

      @posts = @posts.eaten if params[:eaten] == '1'
      @posts = @posts.smelly if params[:smell] == '1'
      @posts = @posts.noisy if params[:sound] == '1'
      @posts = @posts.spilly if params[:spill] == '1'
      @posts = @posts.dirty_hands if params[:hands_dirty] == '1'
      @posts = @posts.by_category(params[:category])
      @posts = @posts.recent.page(params[:page])
  end

  def store_user_return_to
    session[:user_return_to] = posts_random_url if current_user.nil?
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :category, :eaten, :smell, :sound, :spill, :hands_dirty)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= f.radio_button  :category, "food", class:"radio"  %>
    <%= f.label :category_food, "食べ物" %>

    <%= f.radio_button :category, "drink", class:"radio" %>
    <%= f.label :category_drink, "飲み物" %>
  </div>

  <div class="my-5">
    <%= f.check_box :eaten, class: "checkbox" %>
    <%= f.label :eaten, "食べたことがある" %>
  </div>

  <div class="my-5">
    <%= f.label :title, "商品名（必須）" %>
    <%= f.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= f.label :body, "一言コメント（必須）" %>
    <%= f.text_area :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= f.label :image, "画像" %>
    <%= f.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

職場では気になるかもしれないポイント
  <div class="my-5">
    <%= f.check_box :smell, class: "checkbox" %>
    <%= f.label :smell, "匂いがある" %>
  </div>

  <div class="my-5">
    <%= f.check_box :sound, class: "checkbox" %>
    <%= f.label :sound, "音がする" %>
  </div>

  <div class="my-5">
    <%= f.check_box :spill, class: "checkbox" %>
    <%= f.label :spill, "こぼしやすい" %>
  </div>

  <div class="my-5">
    <%= f.check_box :hands_dirty, class: "checkbox" %>
    <%= f.label :hands_dirty, "手が汚れる" %>
  </div>

  <div class="inline">
    <%= f.submit "送信", class: "btn btn-primary mb-4" %>
  </div>
<% end %>

app/views/posts/_full_post.html.erb
<div class="card w-full max-w-lg bg-base-100 shadow-xl my-6 mx-auto">
  <figure>
  <%= image_tag post.image.url(:index_size), class: "object-contain" %>
  </figure>
  <div class="card-body">
    <div class="text-right">
      <%= render 'like_button', post: post %>
    </div>
    <div class="flex items-center mb-2">
      <%= image_tag post.user.profile.avatar.url(:index_size), class: "w-10 h-10 rounded-full object-cover mr-2" %>
      <%= post.user.profile.name %>
    </div>

    <h2 class="card-title text-lg h-8 mb-2"><%= post.title %></h2>

    <div class="badge badge-outline w-full h-8 flex items-center justify-center">
    <%= post.category == "food" ? "食べ物" : "飲み物"%>
    </div>

    <% if post.eaten %>
      <p class="badge badge-outline w-full h-8 flex items-center justify-center">食べたことがある</p>
    <% else %>
      <p class="badge badge-outline w-full h-8 flex items-center justify-center" >食べたことはない</p>
    <% end %>

    <div class="card-actions justify-light">
      <% if post.smell || post.sound || post.spill || post.hands_dirty %>
        <% if post.smell %>
          <div class="badge badge-secondary w-full h-8 flex items-center justify-center">匂いがある</div>
        <% end %>
        <% if post.sound %>
          <div class="badge badge-secondary w-full h-8 flex items-center justify-center">音がする</div>
        <% end %>
        <% if post.spill %>
          <div class="badge badge-secondary  w-full h-8 flex items-center justify-center">こぼしやすい</div>
        <% end %>
        <% if post.hands_dirty %>
          <div class="badge badge-secondary  w-full h-8 flex items-center justify-center">手が汚れる</div>
        <% end %>
      <% else %>
        <p class="badge badge-accent w-full h-8 flex items-center justify-center" >職場でも気にならない！</p>
      <% end %>
    </div>

  <div class="rounded border p-3 text-sm my-2 w-full" >
    <%= post.body %>
  </div>

    <div class="card-actions justify-end mt-2">
    <% if current_user.own?(post) %>
      <%= link_to edit_post_path(post), class: "btn btn-ghost mr-1" do %>
        <i class="fa-solid fa-pen-to-square fa-lg" style="color:#f4a460"></i>
      <% end %>
      <%= button_to post_path(post), method: :delete,  class: "btn btn-ghost mr-1" do %>
        <i class="fa-solid fa-trash fa-lg" style="color:#4682b4"></i>
        <% end %>
      <% end %>
      <%= link_to "一覧に戻る", posts_path, class: "btn btn-ghost" %>
    </div>
  </div>
</div>

app/views/posts/_like_button.html.erb
<turbo-frame id="like-button-<%= post.id %>">
  <% if current_user.like?(post) %>
    <%= link_to like_path(current_user.likes.find_by(post_id: post.id)),  data: { turbo_method: :delete } do %>
      <i class="fa-solid fa-heart fa-lg" style="color:#fa8072"></i>
    <% end %>
  <% else %>
    <%= link_to likes_path(post_id: post.id),  data: { turbo_method: :post } do %>
      <i class="fa-regular fa-heart fa-lg" style="color:#fa8072"></i>
    <% end %>
  <% end %>
</turbo-frame>

app/views/posts/_post.html.erb
<div class="card w-full max-w-lg bg-base-100 shadow-xl my-2 mx-auto">
  <figure class="aspect-w-4 aspect-h-5">
  <%= image_tag post.image.url(:index_size), class: "object-cover" %>
  </figure>
  <div class="card-body">

    <div class="text-right">
      <%= render 'like_button', post: post %>
    </div>
    <div class="flex items-center mb-1">
      <%= image_tag post.user.profile.avatar.url(:index_size), class: "w-10 h-10 rounded-full object-cover mr-2" %>
      <%= post.user.profile.name %>
    </div>
    <h2 class="card-title text-lg h-8 mb-2"><%= post.title %></h2>
      <% if post.smell || post.sound || post.spill || post.hands_dirty %>
        <div class="badge badge-secondary w-full h-8 flex items-center justify-center">職場だと気になるかも？</div>
      <% else %>
        <div class="badge badge-accent w-full h-8 flex items-center justify-center">職場でも気にならない！</div>
      <% end %>
    <div class="card-actions justify-end mt-4">
      <%= link_to "詳細", post, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/posts/_search.html.erb
<div id="accordion">
  <div class="accordion-item">
    <button class="btn btn-active mb-2">絞り込み検索</button>
    <div class="accordion-content hidden">

      <%= form_with url: posts_path, method: :get do |f| %>

        <div class="my-3">
          <%= f.check_box :eaten, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :eaten, '食べたことがある' %>
        </div>

        <div class="my-3">
          <%= f.check_box :smell, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :smell, '匂いが気になる' %>
        </div>

        <div class="my-3">
          <%= f.check_box :sound, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :sound, '音がする' %>
        </div>

        <div class="my-3">
          <%= f.check_box :spill, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :spill, 'こぼしやすい' %>
        </div>

        <div class="my-3">
          <%= f.check_box :hands_dirty, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :hands_dirty, '手が汚れる' %>
        </div>

        <div class="my-3">
          <%= f.select :category, [['食べ物', 0], ['飲み物', 1]], {}, { class: 'select select-bordered' } %>
        </div>

        <div class="my-3">
          <%= f.submit '検索',class: "btn btn-accent" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
  document.querySelectorAll('.btn').forEach(button => {
    button.addEventListener('click', function() {
      const accordionContent = button.nextElementSibling;
      accordionContent.classList.toggle('hidden');
    });
  });
</script>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">編集</h1>

  <%= render "form", post: @post %>

  <%= link_to "戻る", post_path, class: "btn" %>
</div>

app/views/posts/index.html.erb
<div class="w-full px-4">
  <h1 class="font-bold text-2xl">投稿一覧</h1>
  <%= link_to "投稿する", new_post_path, class: "btn btn-primary my-4" %>
  <%= render partial: "posts/search" %>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">
    <%= render @posts %>
  </div>

  <div class="flex justify-center mt-6 mb-2">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/likes.html.erb
<div class="w-full px-4">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">お気に入り一覧</h1>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">

    <%= render @posts %>

  </div>
  <div class="flex justify-center mt-6 mb-2">
  <%= paginate @posts %>
  </div>
</div>

app/views/posts/my_posts.html.erb
<div class="w-full px-4">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">自分の投稿一覧</h1>
    <%= link_to "投稿する", new_post_path, class: "btn btn-primary" %>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">

    <%= render @posts %>

  </div>
  <div class="flex justify-center mt-6 mb-2">
  <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">投稿する</h1>

  <%= render "form", post: @post %>

</div>

app/views/posts/random.html.erb
<div class=" flex flex-col items-center w-full px-4">
  <div class="mx-auto">
    <h1 class="font-bold text-2xl">ランダムピックアップ</h1>

    <%= render partial: "posts/full_post", locals: { post: @post } %>

  </div>
</div>

app/views/posts/search.html.erb
<div class="w-full">
  <h1 class="font-bold text-2xl">絞り込み検索</h1>

<div id="accordion">
  <div class="accordion-item">
    <button class="btn btn-primary mt-4">絞り込み検索</button>
    <div class="accordion-content hidden">

      <%= form_with url: search_posts_path, method: :get do |f| %>

        <div class="my-3">
          <%= f.check_box :eaten, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :eaten, '食べたことがある' %>
        </div>

        <div class="my-3">
          <%= f.check_box :smell, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :smell, '匂いが気になる' %>
        </div>

        <div class="my-3">
          <%= f.check_box :sound, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :sound, '音がする' %>
        </div>

        <div class="my-3">
          <%= f.check_box :spill, { class: 'checkbox' }, '1', '0' %>
          <%= f.label :spill, 'こぼしやすい' %>
        </div>

        <div class="my-3">
          <%= f.select :category, [['食べ物', 0], ['飲み物', 1]], {}, { class: 'select select-bordered' } %>
        </div>

        <div class="my-3">
          <%= f.submit '検索',class: "btn btn-accent" %>
        </div>
      <% end %>

    </div>
  </div>
</div>


<script>
  document.querySelectorAll('.btn').forEach(button => {
    button.addEventListener('click', function() {
      const accordionContent = button.nextElementSibling;
      accordionContent.classList.toggle('hidden');
    });
  });
</script>


  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">
    <% if @posts.present? %>
      <%= render @posts %>
      <div>
        <%= paginate @posts, class: "flex justify-center mb-2" %>
      </div>
    <% else %>
      <p>該当する投稿はありません。</p>
    <% end %>
  </div>

</div>

app/views/posts/show.html.erb
<div class=" flex flex-col items-center w-full px-4">
  <div class="w-full max-w-lg">
    <h1 class="font-bold text-2xl">投稿詳細</h1>
    <div class="mb-2">
    <%= render partial: "posts/full_post", locals: { post: @post } %>

    <%= turbo_frame_tag "new_comment" do %>
      <%= render 'comments/form', post: @post, comment: @comment %>
    <% end %>

    <%= turbo_frame_tag "comments" do %>
      <%= render 'comments/comments', comments: @comments %>
    <% end %>

    </div>
  </div>
</div>